version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - hdbank-net
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hdbankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hdbank-net

volumes:
  pgdata:
  jenkins_home:

networks:
  hdbank-net:
