spring:
  application:
    name: Hdbank_project
  datasource:
    url: jdbc:postgresql://localhost:5432/hdbankdb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8888
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter: DEBUG